import type { Metadata } from "next";
import "../styles/globals.css"
import Header from "@/components/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className="min-h-screen flex flex-col">
				
				{children}
			</body>
		</html>
	);
}
